PaddlePaddle/PLSC

plsc/entry.py
remove input function and add message when overwriting the local dir.
=> remove input function and add message when overwriting the local dir.

README.md
delete update notes from README.md as we have added the release notes
=> delete update notes from README.md as we have added the release notes

plsc/entry.py, plsc/version.py
1. fix the hange issue if checkpoint_dir is specified but not exists
2. update version to 0.1.1
=> fix the hange issue if checkpoint_dir is specified but not exists and update version to 0.1.1

requirements.txt, setup.py
remove duplicate dependences with paddlepaddle
=> remove duplicate dependences with paddlepaddle

requirements.txt, setup.py
keep requirement.txt consistence with the latest paddlepaddle
=> keep requirement.txt consistence with the latest paddlepaddle

plsc/entry.py
Fix the format for outputing acc values.
=> fix the output format for acc values.

plsc/entry.py
parameterize lr_decay_factor, step_boundaries and log_period, so use can change default values for these parameters.
=> parameterize lr_decay_factor, step_boundaries and log_period

plsc/models/resnet.py
align the implementation of resnet152 to the implementation in mxnet/insight
=> align the implementation of resnet152 to the implementation in mxnet/insight

plsc/entry.py
remove program_to_code because the api is deleted from the framework.
=> remove program_to_code

plsc/entry.py, plsc/models/base_model.py, plsc/models/resnet.py, plsc/utils/input_field.py
Modify the reader to support universal inputs for training。
=> Support universal inputs

demo/data_loader.py, demo/demo_noncv.py
delete the use of paddle.batch
=> bug fix: fix the use of dataloader

plsc/entry.py
fix the use of data loader and the default value for data input shape
=> fix the use of data loader and the default value for data input shape

docs/source/md/serving.md
=> fix a deadlink in serving.md

plsc/entry.py
=> add quantization

plsc/config.py, plsc/entry.py, plsc/models/base_model.py, plsc/models/dist_algo.py, plsc/models/resnet.py, train.py, train.sh
* support Partial FC
* support cosface loss function
* support resnet100
* remove softmax and dist-softmax loss pass
* using model_parallel flag to replace dist-* loss type statement
* using margin loss to unify arcface, cosface, sphereface, softmax loss function
=> support Partial FC and Margin Loss

plsc/config.py, plsc/entry.py, plsc/models/base_model.py, plsc/models/dist_algo.py, plsc/models/resnet.py, train.py, train.sh
* support Partial FC
* support cosface loss function
* support resnet100
* remove softmax and dist-softmax loss pass
* using model_parallel flag to replace dist-* loss type statement
* using margin loss to unify arcface, cosface, sphereface, softmax loss function
=> support Partial FC and Cosface loss function

plsc/entry.py, plsc/models/base_model.py, plsc/models/dist_algo.py, plsc/models/resnet.py
=> fix res100 bug

plsc/entry.py, plsc/models/base_model.py, plsc/models/dist_algo.py, plsc/models/resnet.py
=> fix res100 bug (#86)

scripts/ce_benchmark.sh
* modes=("static" "dynamic")
* dtypes=("FP16" "FP32")
* data_formats=("NHWC" "NCHW")
* gpus=("0" "0,1,2,3")
* sample_ratios=(0.1 1.0)
there are 32 experiments to run
=> add ce benchmark

dynamic/train.py, requirement.txt, scripts/find_maximum_classes_dynamic.sh, scripts/find_maximum_classes_static.sh, static/static_model.py, static/train.py
* remove duplicate opencv-python in requirement.txt
* remove unused visualdl
* fix the maximum number class of ``dynamic`` and ``static`` for PaddlePaddle 2.2.2
=> fix some bug

dynamic/utils/hybrid_optimizer.py
In order to compatible upgrade of sparse_momentum for master param, add try-catch block for sparse_momentum.
=> compatible upgrade of sparse_momentum for master param

plsc/configs/VisionTransformer/ViT_base_patch16_224_in1k_4n32c_dp_fp16o1.yaml, plsc/configs/VisionTransformer/ViT_base_patch16_224_in1k_4n32c_dp_fp16o2.yaml, plsc/configs/VisionTransformer/ViT_base_patch16_384_ft_in1k_4n32c_dp_fp16o2.yaml, plsc/configs/VisionTransformer/ViT_large_patch16_384_in1k_ft_1n8c_dp_fp16o2.yaml, plsc/configs/VisionTransformer/ViT_large_patch16_384_in1k_ft_4n32c_dp_fp16o2.yaml, plsc/core/grad_clip.py, plsc/data/dataset/common_dataset.py, plsc/engine/classification/train.py, plsc/engine/engine.py, plsc/engine/recognition/train.py, plsc/loss/celoss.py, plsc/models/vision_transformer.py, plsc/optimizer/momentum.py, tools/eval.py
* ViT-B/16 finetune, Top1 Acc: 0.7805, while ViT paper was 0.7791. There is diff:
* lr from 0.03 to 0.003
* add 0.0001 weight_decay
* global gradient clip from 1.0 to 0.5
* ViT-L/16 finetune, Top1 Acc 85.03% based on JAX checkpoint, while ViT GitHub was 85.05%.
* add 0.0001 weight decay for Momentum optimizer
=> Vit finetune

README.md, plsc/configs/VisionTransformer/ViT_base_patch16_224_in1k_1n8c_dp_fp16o2.yaml, plsc/configs/VisionTransformer/ViT_base_patch16_384_ft_in1k_1n8c_dp_fp16o2.yaml, setup.py, task/classification/vit/README.md, tutorials/get_started/installation.md, version.py
* add vit-b_16 pretrain and finetune yaml on 1nc8
* add setup.py
* add vit docs
* update readme
=> add vit-b_16 pretrain and finetune yaml on 1nc8

plsc/models/layers/partialfc.py, plsc/nn/norm.py
Fix the problem caused by removing fluid.layers.l2_normalize in paddle [PR#48274](https://github.com/PaddlePaddle/Paddle/pull/48274)
=> Fix the problem caused by removing fluid.layers.l2_normalize

plsc/models/utils/tome.py
=> fix ToMeVisionTransformer

README.md, plsc/engine/classification/evaluation.py, plsc/engine/classification/train.py, plsc/engine/engine.py, plsc/models/__init__.py, plsc/models/convnext.py, plsc/models/utils/__init__.py, plsc/models/utils/ema.py, plsc/scheduler/lr_scheduler.py, plsc/utils/io.py, task/classification/convnext/README.md, task/classification/convnext/configs/ConvNeXt_base_224_in1k_1n8c_dp_fp32.yaml, task/classification/convnext/configs/ConvNeXt_base_224_in1k_4n32c_dp_fp16O2.yaml, task/classification/convnext/configs/ConvNeXt_base_224_in1k_4n32c_dp_fp32.yaml, tests/CI/case.sh, tests/CI/classification/convnext/ConvNeXt_base_224_in1k_1n8c_dp_fp32.sh
1. add convnext model
2. add config file(fp32)
=> feat: add convnext model and config
